basePath: /api/v1
definitions:
  common.ChangePassword:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  common.ErrorOnly:
    properties:
      error:
        type: string
    type: object
  common.ResultWithErrors:
    properties:
      error:
        type: string
      result:
        type: string
    type: object
  database.Admin:
    properties:
      id:
        type: integer
      login:
        type: string
      password:
        type: string
    type: object
  database.Entry:
    properties:
      comment:
        type: string
      count_members:
        type: integer
      email:
        type: string
      id:
        type: integer
      is_need_lunch:
        type: boolean
      is_need_notify:
        type: boolean
      name:
        type: string
      phone:
        type: string
      scheduled_tour_id:
        type: integer
      telegram_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: Ruin keepers
  version: "0.1"
paths:
  /admin/changePassword:
    post:
      parameters:
      - description: Данные для смены пароля
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/common.ChangePassword'
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      tags:
      - admin
  /admin/delete:
    post:
      parameters:
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      tags:
      - admin
  /admin/login:
    post:
      parameters:
      - description: Данные админа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Admin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      tags:
      - admin
  /admin/register:
    post:
      parameters:
      - description: Данные админа
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Admin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      tags:
      - admin
  /admin/tours/add:
    post:
      parameters:
      - description: Данные тура
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Entry'
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ErrorOnly'
      tags:
      - admin tours
  /admin/tours/delete:
    post:
      parameters:
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID тура
        in: query
        name: tourId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ErrorOnly'
      tags:
      - admin tours
  /admin/tours/update:
    post:
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Entry'
      - description: Токен авторизации
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID тура
        in: query
        name: tourId
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ErrorOnly'
      tags:
      - admin tours
  /tours/all:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      summary: получение туров
      tags:
      - tours
  /tours/scheduledTourById:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      summary: получение расписания туров по id
      tags:
      - tours
  /tours/scheduledTours:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      summary: получение расписания туров
      tags:
      - tours
  /tours/signUpToTour:
    get:
      parameters:
      - description: Данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/database.Entry'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      tags:
      - tours
  /tours/tourById:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.ResultWithErrors'
      summary: получение туров по id
      tags:
      - tours
schemes:
- http
swagger: "2.0"
